### ISSUE TITLE
`Specification` `C`/`C++` design

### ISSUE THREAD

**Issue by foundrytom** [TheFoundryVisionmongers/OpenAssetIO#226]
## What

Re-visit the current implementation choices for the Specification type system through the new lens of our `C`/`C++`/`Python` core language strategy. Decide upon the approach moving forward.

## Why

The current implementation, though functional and meeting the design goals for the system, has a few issues:

 - Makes use of python tricks (`metaclass`, etc) which have no direct alternative in the `C++` core space.
 - Encourages the use of classical inheritance as a runtime technique for identification which is not a good fit for many target languages and conflates syntax with business logic.
 - The `SpecificationBase`/`Specification` structure, though well intended, is clunky and not well thought out.
 
## Background

Specifications are the core of OpenAssetIO. They are used to define the type of entities as well as describe relationships and the details of a calling context (locale). There are several hard requirements for their implementation, they must be:

  - Hierarchical/Composable (to support "upcasting" to known specifications or traits)
  - Simple in structure (to simple data types for interop/serialisation)
  - Robust (compile-time checks for programming errors - property access or invalid method arguments)
  - Discoverable (runtime introspection/help)
  - Definable out of core (by host integrations/managers)

More details on Specifications are available [here](https://thefoundryvisionmongers.github.io/OpenAssetIO/entities_specifications_and_attributes.html).

## Acceptance Criteria

- A decision record for the choice to use hierarchy or trait composition
- A design for the Specifications API/implementation that meets the above criteria and fits well with our core language strategy.

## Out of scope

- Defining a library of specifications
- The details of any specific specification and/or its properties

## Pre-planning tasks

-  [x] Hierarchy .vs. composition are we keeping the existing data model?
-  [x] What prior art is applicable? ([`usdSchemaGen`](https://graphics.pixar.com/usd/release/tut_generating_new_schema.html), [OTIO SchemaDef](https://opentimelineio.readthedocs.io/en/latest/tutorials/write-a-schemadef.html))

**Comment by foundrytom** [comment]
We should tackle the topic of hierarchy .vs. composition in the style of a "PhD defence" around #230. Where we need to demonstrate that there isn't a superior solution to the existing specification data model and approach that uses a "single parent" hierarchical taxonomy.

**Comment by feltech** [comment]
Added a [wiki page](https://github.com/TheFoundryVisionmongers/OpenAssetIO/wiki/Investigation:-prior-art-in-schema-implementations) for investigations of prior art in extensible schema implementations.

**Comment by foundrytom** [comment]
Some notes from offline conversations about broader workflows follow.

From a product perspective, there are several core requirements for the Specifications system as noted above, we had not spoken directly about relative priority before, but this is the order of importance, form most to least:

1. Extensible - definable out of core (by host integrations/managers)
2. Hierarchical/Composable (to support "upcasting" to known specifications or traits)
3. Simple in structure (to simple data types for interop/serialisation)
4. Robust (compile-time checks for programming errors - property access or invalid method arguments)
5. Discoverable (runtime introspection/help)

Some details of the less obvious practical applications of these topics through terrible, but hopefully illustrative pseudocode:

## Photoshop swatch publishing

This covers the **extensibility**, **composability** and **simple/serializable**. 

Imagine an integration into Photoshop, using its JavaScript based SDK, wants to publish a colour swatch library (proprietary photoshop file format). 

The following should be possible, without needing complex, additional compiled runtime plugins (setting all this up in a typical production design environment is somewhat more arduous than a mass-managed linux studio deployment).

### photoshopPublish.js
```javascript
const swatchTraits = [ 'blob', 'color', 'swatch', 'photoshop' ]
...
let publishedRref = await manager.register( [swatchPath,], [{'traits': swatchTraits},], context )
...
````

### myManager.py
```python

def register(self, references, specs, context):
     for ref, spec in zip(references, spec):
         if spec.hasTrait(openassetio.specifications.traits.BlobTrait):
            self.handleBlobRegistration(ref, spec, context)
         else:
            self.handleGenericRegistration(ref, spec, context)
```

## Auditing and manifest generation

This primarily covers **simple/serializable**, but informs **extensible**

OpenAssetIO provides an auditing mechanism that can track all API calls made through it.  In this workflow, a captured render process is used to generate a flat manifest of dependent asset URLs. This is done using code that handles custom specifications used by `anApp`, without any direct knowledge, specific handling or additional runtime requirements.

### anApp.py
```python

capture = session.captureCalls("renderAssetCalls.yml", calls=["resolveEntityReference",])
doRender(targetNode)
capture.stop()
```

### renderAssetCalls.yml
```yaml
manager:
  com.yourCompany.ams:
    calls:
      resolveEntityReference: [
         {
            refs: ["asset:///a"],
            context: {
               access: read,
               locale: {
                 traits: ["nuke", "node", "read", "image"],
                 props: { "node:name": "ImageRead1" }
               } 
             },
        {
            refs: ["asset:///b"],
            context: {
               access: read,
               locale: {
                 traits: ["nuke", "node", "read", "scene"],
                 props: { "node:name": "USDIn" }
               } 
             },
        {
            refs: ["asset:///c"],
            context: {
               access: write,
               locale: {
                 traits: ["nuke", "node", "write", "image"],
                 props: { "node:name": "Write4" }
               } 
             },
        }
     ]
```

### resolveDeps.py
```python
def getDeps(capturedCalls):
     """
     Collects the URLs to all of the data dependencies required by a captured set
     of API calls.
     """
     ... 
     allDeps = []

     calls = capturedCalls["manager"]["com.yourCompany.ams"]["calls"]["resolveEntityReference"]
     for call in calls:

        context = Context()
        context.access = call["context"]["access"]
        context.locale = Specification(
               traits=call["context"]["locale"]["traits"],
               props=call["context"]["locale"]["props"]
        )

        allDeps.extend(manager.resovleEntityReference(call["refs"], context))

        # Ask the manager for any other internal depencies this entity may have
        depRefs = manager.getRelatedReferences(refs, [openassetio.specs.relationship.DataDependencySpec()], context):
            allDeps.extend(manager.resolveEntityReference(depRefs, context))

   return allDeps
```
